// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clicksCount.proto

package io.confluent.training.proto;

public final class ClicksCountProtos {
  private ClicksCountProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ClicksCountOrBuilder extends
      // @@protoc_insertion_point(interface_extends:io.confluent.training.proto.ClicksCount)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.google.protobuf.StringValue session_start_ts = 1;</code>
     * @return Whether the sessionStartTs field is set.
     */
    boolean hasSessionStartTs();
    /**
     * <code>.google.protobuf.StringValue session_start_ts = 1;</code>
     * @return The sessionStartTs.
     */
    com.google.protobuf.StringValue getSessionStartTs();
    /**
     * <code>.google.protobuf.StringValue session_start_ts = 1;</code>
     */
    com.google.protobuf.StringValueOrBuilder getSessionStartTsOrBuilder();

    /**
     * <code>.google.protobuf.StringValue session_end_ts = 2;</code>
     * @return Whether the sessionEndTs field is set.
     */
    boolean hasSessionEndTs();
    /**
     * <code>.google.protobuf.StringValue session_end_ts = 2;</code>
     * @return The sessionEndTs.
     */
    com.google.protobuf.StringValue getSessionEndTs();
    /**
     * <code>.google.protobuf.StringValue session_end_ts = 2;</code>
     */
    com.google.protobuf.StringValueOrBuilder getSessionEndTsOrBuilder();

    /**
     * <code>.google.protobuf.Int64Value click_count = 3;</code>
     * @return Whether the clickCount field is set.
     */
    boolean hasClickCount();
    /**
     * <code>.google.protobuf.Int64Value click_count = 3;</code>
     * @return The clickCount.
     */
    com.google.protobuf.Int64Value getClickCount();
    /**
     * <code>.google.protobuf.Int64Value click_count = 3;</code>
     */
    com.google.protobuf.Int64ValueOrBuilder getClickCountOrBuilder();

    /**
     * <code>.google.protobuf.Int64Value session_length_ms = 4;</code>
     * @return Whether the sessionLengthMs field is set.
     */
    boolean hasSessionLengthMs();
    /**
     * <code>.google.protobuf.Int64Value session_length_ms = 4;</code>
     * @return The sessionLengthMs.
     */
    com.google.protobuf.Int64Value getSessionLengthMs();
    /**
     * <code>.google.protobuf.Int64Value session_length_ms = 4;</code>
     */
    com.google.protobuf.Int64ValueOrBuilder getSessionLengthMsOrBuilder();
  }
  /**
   * Protobuf type {@code io.confluent.training.proto.ClicksCount}
   */
  public static final class ClicksCount extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:io.confluent.training.proto.ClicksCount)
      ClicksCountOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ClicksCount.newBuilder() to construct.
    private ClicksCount(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ClicksCount() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ClicksCount();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ClicksCount(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.StringValue.Builder subBuilder = null;
              if (sessionStartTs_ != null) {
                subBuilder = sessionStartTs_.toBuilder();
              }
              sessionStartTs_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(sessionStartTs_);
                sessionStartTs_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              com.google.protobuf.StringValue.Builder subBuilder = null;
              if (sessionEndTs_ != null) {
                subBuilder = sessionEndTs_.toBuilder();
              }
              sessionEndTs_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(sessionEndTs_);
                sessionEndTs_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              com.google.protobuf.Int64Value.Builder subBuilder = null;
              if (clickCount_ != null) {
                subBuilder = clickCount_.toBuilder();
              }
              clickCount_ = input.readMessage(com.google.protobuf.Int64Value.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(clickCount_);
                clickCount_ = subBuilder.buildPartial();
              }

              break;
            }
            case 34: {
              com.google.protobuf.Int64Value.Builder subBuilder = null;
              if (sessionLengthMs_ != null) {
                subBuilder = sessionLengthMs_.toBuilder();
              }
              sessionLengthMs_ = input.readMessage(com.google.protobuf.Int64Value.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(sessionLengthMs_);
                sessionLengthMs_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.confluent.training.proto.ClicksCountProtos.internal_static_io_confluent_training_proto_ClicksCount_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.confluent.training.proto.ClicksCountProtos.internal_static_io_confluent_training_proto_ClicksCount_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.confluent.training.proto.ClicksCountProtos.ClicksCount.class, io.confluent.training.proto.ClicksCountProtos.ClicksCount.Builder.class);
    }

    public static final int SESSION_START_TS_FIELD_NUMBER = 1;
    private com.google.protobuf.StringValue sessionStartTs_;
    /**
     * <code>.google.protobuf.StringValue session_start_ts = 1;</code>
     * @return Whether the sessionStartTs field is set.
     */
    @java.lang.Override
    public boolean hasSessionStartTs() {
      return sessionStartTs_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue session_start_ts = 1;</code>
     * @return The sessionStartTs.
     */
    @java.lang.Override
    public com.google.protobuf.StringValue getSessionStartTs() {
      return sessionStartTs_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : sessionStartTs_;
    }
    /**
     * <code>.google.protobuf.StringValue session_start_ts = 1;</code>
     */
    @java.lang.Override
    public com.google.protobuf.StringValueOrBuilder getSessionStartTsOrBuilder() {
      return getSessionStartTs();
    }

    public static final int SESSION_END_TS_FIELD_NUMBER = 2;
    private com.google.protobuf.StringValue sessionEndTs_;
    /**
     * <code>.google.protobuf.StringValue session_end_ts = 2;</code>
     * @return Whether the sessionEndTs field is set.
     */
    @java.lang.Override
    public boolean hasSessionEndTs() {
      return sessionEndTs_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue session_end_ts = 2;</code>
     * @return The sessionEndTs.
     */
    @java.lang.Override
    public com.google.protobuf.StringValue getSessionEndTs() {
      return sessionEndTs_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : sessionEndTs_;
    }
    /**
     * <code>.google.protobuf.StringValue session_end_ts = 2;</code>
     */
    @java.lang.Override
    public com.google.protobuf.StringValueOrBuilder getSessionEndTsOrBuilder() {
      return getSessionEndTs();
    }

    public static final int CLICK_COUNT_FIELD_NUMBER = 3;
    private com.google.protobuf.Int64Value clickCount_;
    /**
     * <code>.google.protobuf.Int64Value click_count = 3;</code>
     * @return Whether the clickCount field is set.
     */
    @java.lang.Override
    public boolean hasClickCount() {
      return clickCount_ != null;
    }
    /**
     * <code>.google.protobuf.Int64Value click_count = 3;</code>
     * @return The clickCount.
     */
    @java.lang.Override
    public com.google.protobuf.Int64Value getClickCount() {
      return clickCount_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : clickCount_;
    }
    /**
     * <code>.google.protobuf.Int64Value click_count = 3;</code>
     */
    @java.lang.Override
    public com.google.protobuf.Int64ValueOrBuilder getClickCountOrBuilder() {
      return getClickCount();
    }

    public static final int SESSION_LENGTH_MS_FIELD_NUMBER = 4;
    private com.google.protobuf.Int64Value sessionLengthMs_;
    /**
     * <code>.google.protobuf.Int64Value session_length_ms = 4;</code>
     * @return Whether the sessionLengthMs field is set.
     */
    @java.lang.Override
    public boolean hasSessionLengthMs() {
      return sessionLengthMs_ != null;
    }
    /**
     * <code>.google.protobuf.Int64Value session_length_ms = 4;</code>
     * @return The sessionLengthMs.
     */
    @java.lang.Override
    public com.google.protobuf.Int64Value getSessionLengthMs() {
      return sessionLengthMs_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : sessionLengthMs_;
    }
    /**
     * <code>.google.protobuf.Int64Value session_length_ms = 4;</code>
     */
    @java.lang.Override
    public com.google.protobuf.Int64ValueOrBuilder getSessionLengthMsOrBuilder() {
      return getSessionLengthMs();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (sessionStartTs_ != null) {
        output.writeMessage(1, getSessionStartTs());
      }
      if (sessionEndTs_ != null) {
        output.writeMessage(2, getSessionEndTs());
      }
      if (clickCount_ != null) {
        output.writeMessage(3, getClickCount());
      }
      if (sessionLengthMs_ != null) {
        output.writeMessage(4, getSessionLengthMs());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (sessionStartTs_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getSessionStartTs());
      }
      if (sessionEndTs_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getSessionEndTs());
      }
      if (clickCount_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getClickCount());
      }
      if (sessionLengthMs_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getSessionLengthMs());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.confluent.training.proto.ClicksCountProtos.ClicksCount)) {
        return super.equals(obj);
      }
      io.confluent.training.proto.ClicksCountProtos.ClicksCount other = (io.confluent.training.proto.ClicksCountProtos.ClicksCount) obj;

      if (hasSessionStartTs() != other.hasSessionStartTs()) return false;
      if (hasSessionStartTs()) {
        if (!getSessionStartTs()
            .equals(other.getSessionStartTs())) return false;
      }
      if (hasSessionEndTs() != other.hasSessionEndTs()) return false;
      if (hasSessionEndTs()) {
        if (!getSessionEndTs()
            .equals(other.getSessionEndTs())) return false;
      }
      if (hasClickCount() != other.hasClickCount()) return false;
      if (hasClickCount()) {
        if (!getClickCount()
            .equals(other.getClickCount())) return false;
      }
      if (hasSessionLengthMs() != other.hasSessionLengthMs()) return false;
      if (hasSessionLengthMs()) {
        if (!getSessionLengthMs()
            .equals(other.getSessionLengthMs())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasSessionStartTs()) {
        hash = (37 * hash) + SESSION_START_TS_FIELD_NUMBER;
        hash = (53 * hash) + getSessionStartTs().hashCode();
      }
      if (hasSessionEndTs()) {
        hash = (37 * hash) + SESSION_END_TS_FIELD_NUMBER;
        hash = (53 * hash) + getSessionEndTs().hashCode();
      }
      if (hasClickCount()) {
        hash = (37 * hash) + CLICK_COUNT_FIELD_NUMBER;
        hash = (53 * hash) + getClickCount().hashCode();
      }
      if (hasSessionLengthMs()) {
        hash = (37 * hash) + SESSION_LENGTH_MS_FIELD_NUMBER;
        hash = (53 * hash) + getSessionLengthMs().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.confluent.training.proto.ClicksCountProtos.ClicksCount parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.confluent.training.proto.ClicksCountProtos.ClicksCount parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.confluent.training.proto.ClicksCountProtos.ClicksCount parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.confluent.training.proto.ClicksCountProtos.ClicksCount parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.confluent.training.proto.ClicksCountProtos.ClicksCount parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.confluent.training.proto.ClicksCountProtos.ClicksCount parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.confluent.training.proto.ClicksCountProtos.ClicksCount parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.confluent.training.proto.ClicksCountProtos.ClicksCount parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.confluent.training.proto.ClicksCountProtos.ClicksCount parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.confluent.training.proto.ClicksCountProtos.ClicksCount parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.confluent.training.proto.ClicksCountProtos.ClicksCount parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.confluent.training.proto.ClicksCountProtos.ClicksCount parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.confluent.training.proto.ClicksCountProtos.ClicksCount prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code io.confluent.training.proto.ClicksCount}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:io.confluent.training.proto.ClicksCount)
        io.confluent.training.proto.ClicksCountProtos.ClicksCountOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.confluent.training.proto.ClicksCountProtos.internal_static_io_confluent_training_proto_ClicksCount_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.confluent.training.proto.ClicksCountProtos.internal_static_io_confluent_training_proto_ClicksCount_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.confluent.training.proto.ClicksCountProtos.ClicksCount.class, io.confluent.training.proto.ClicksCountProtos.ClicksCount.Builder.class);
      }

      // Construct using io.confluent.training.proto.ClicksCountProtos.ClicksCount.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (sessionStartTsBuilder_ == null) {
          sessionStartTs_ = null;
        } else {
          sessionStartTs_ = null;
          sessionStartTsBuilder_ = null;
        }
        if (sessionEndTsBuilder_ == null) {
          sessionEndTs_ = null;
        } else {
          sessionEndTs_ = null;
          sessionEndTsBuilder_ = null;
        }
        if (clickCountBuilder_ == null) {
          clickCount_ = null;
        } else {
          clickCount_ = null;
          clickCountBuilder_ = null;
        }
        if (sessionLengthMsBuilder_ == null) {
          sessionLengthMs_ = null;
        } else {
          sessionLengthMs_ = null;
          sessionLengthMsBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.confluent.training.proto.ClicksCountProtos.internal_static_io_confluent_training_proto_ClicksCount_descriptor;
      }

      @java.lang.Override
      public io.confluent.training.proto.ClicksCountProtos.ClicksCount getDefaultInstanceForType() {
        return io.confluent.training.proto.ClicksCountProtos.ClicksCount.getDefaultInstance();
      }

      @java.lang.Override
      public io.confluent.training.proto.ClicksCountProtos.ClicksCount build() {
        io.confluent.training.proto.ClicksCountProtos.ClicksCount result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.confluent.training.proto.ClicksCountProtos.ClicksCount buildPartial() {
        io.confluent.training.proto.ClicksCountProtos.ClicksCount result = new io.confluent.training.proto.ClicksCountProtos.ClicksCount(this);
        if (sessionStartTsBuilder_ == null) {
          result.sessionStartTs_ = sessionStartTs_;
        } else {
          result.sessionStartTs_ = sessionStartTsBuilder_.build();
        }
        if (sessionEndTsBuilder_ == null) {
          result.sessionEndTs_ = sessionEndTs_;
        } else {
          result.sessionEndTs_ = sessionEndTsBuilder_.build();
        }
        if (clickCountBuilder_ == null) {
          result.clickCount_ = clickCount_;
        } else {
          result.clickCount_ = clickCountBuilder_.build();
        }
        if (sessionLengthMsBuilder_ == null) {
          result.sessionLengthMs_ = sessionLengthMs_;
        } else {
          result.sessionLengthMs_ = sessionLengthMsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.confluent.training.proto.ClicksCountProtos.ClicksCount) {
          return mergeFrom((io.confluent.training.proto.ClicksCountProtos.ClicksCount)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.confluent.training.proto.ClicksCountProtos.ClicksCount other) {
        if (other == io.confluent.training.proto.ClicksCountProtos.ClicksCount.getDefaultInstance()) return this;
        if (other.hasSessionStartTs()) {
          mergeSessionStartTs(other.getSessionStartTs());
        }
        if (other.hasSessionEndTs()) {
          mergeSessionEndTs(other.getSessionEndTs());
        }
        if (other.hasClickCount()) {
          mergeClickCount(other.getClickCount());
        }
        if (other.hasSessionLengthMs()) {
          mergeSessionLengthMs(other.getSessionLengthMs());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.confluent.training.proto.ClicksCountProtos.ClicksCount parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.confluent.training.proto.ClicksCountProtos.ClicksCount) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.StringValue sessionStartTs_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> sessionStartTsBuilder_;
      /**
       * <code>.google.protobuf.StringValue session_start_ts = 1;</code>
       * @return Whether the sessionStartTs field is set.
       */
      public boolean hasSessionStartTs() {
        return sessionStartTsBuilder_ != null || sessionStartTs_ != null;
      }
      /**
       * <code>.google.protobuf.StringValue session_start_ts = 1;</code>
       * @return The sessionStartTs.
       */
      public com.google.protobuf.StringValue getSessionStartTs() {
        if (sessionStartTsBuilder_ == null) {
          return sessionStartTs_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : sessionStartTs_;
        } else {
          return sessionStartTsBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.StringValue session_start_ts = 1;</code>
       */
      public Builder setSessionStartTs(com.google.protobuf.StringValue value) {
        if (sessionStartTsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          sessionStartTs_ = value;
          onChanged();
        } else {
          sessionStartTsBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue session_start_ts = 1;</code>
       */
      public Builder setSessionStartTs(
          com.google.protobuf.StringValue.Builder builderForValue) {
        if (sessionStartTsBuilder_ == null) {
          sessionStartTs_ = builderForValue.build();
          onChanged();
        } else {
          sessionStartTsBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue session_start_ts = 1;</code>
       */
      public Builder mergeSessionStartTs(com.google.protobuf.StringValue value) {
        if (sessionStartTsBuilder_ == null) {
          if (sessionStartTs_ != null) {
            sessionStartTs_ =
              com.google.protobuf.StringValue.newBuilder(sessionStartTs_).mergeFrom(value).buildPartial();
          } else {
            sessionStartTs_ = value;
          }
          onChanged();
        } else {
          sessionStartTsBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue session_start_ts = 1;</code>
       */
      public Builder clearSessionStartTs() {
        if (sessionStartTsBuilder_ == null) {
          sessionStartTs_ = null;
          onChanged();
        } else {
          sessionStartTs_ = null;
          sessionStartTsBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue session_start_ts = 1;</code>
       */
      public com.google.protobuf.StringValue.Builder getSessionStartTsBuilder() {
        
        onChanged();
        return getSessionStartTsFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.StringValue session_start_ts = 1;</code>
       */
      public com.google.protobuf.StringValueOrBuilder getSessionStartTsOrBuilder() {
        if (sessionStartTsBuilder_ != null) {
          return sessionStartTsBuilder_.getMessageOrBuilder();
        } else {
          return sessionStartTs_ == null ?
              com.google.protobuf.StringValue.getDefaultInstance() : sessionStartTs_;
        }
      }
      /**
       * <code>.google.protobuf.StringValue session_start_ts = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
          getSessionStartTsFieldBuilder() {
        if (sessionStartTsBuilder_ == null) {
          sessionStartTsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                  getSessionStartTs(),
                  getParentForChildren(),
                  isClean());
          sessionStartTs_ = null;
        }
        return sessionStartTsBuilder_;
      }

      private com.google.protobuf.StringValue sessionEndTs_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> sessionEndTsBuilder_;
      /**
       * <code>.google.protobuf.StringValue session_end_ts = 2;</code>
       * @return Whether the sessionEndTs field is set.
       */
      public boolean hasSessionEndTs() {
        return sessionEndTsBuilder_ != null || sessionEndTs_ != null;
      }
      /**
       * <code>.google.protobuf.StringValue session_end_ts = 2;</code>
       * @return The sessionEndTs.
       */
      public com.google.protobuf.StringValue getSessionEndTs() {
        if (sessionEndTsBuilder_ == null) {
          return sessionEndTs_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : sessionEndTs_;
        } else {
          return sessionEndTsBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.StringValue session_end_ts = 2;</code>
       */
      public Builder setSessionEndTs(com.google.protobuf.StringValue value) {
        if (sessionEndTsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          sessionEndTs_ = value;
          onChanged();
        } else {
          sessionEndTsBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue session_end_ts = 2;</code>
       */
      public Builder setSessionEndTs(
          com.google.protobuf.StringValue.Builder builderForValue) {
        if (sessionEndTsBuilder_ == null) {
          sessionEndTs_ = builderForValue.build();
          onChanged();
        } else {
          sessionEndTsBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue session_end_ts = 2;</code>
       */
      public Builder mergeSessionEndTs(com.google.protobuf.StringValue value) {
        if (sessionEndTsBuilder_ == null) {
          if (sessionEndTs_ != null) {
            sessionEndTs_ =
              com.google.protobuf.StringValue.newBuilder(sessionEndTs_).mergeFrom(value).buildPartial();
          } else {
            sessionEndTs_ = value;
          }
          onChanged();
        } else {
          sessionEndTsBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue session_end_ts = 2;</code>
       */
      public Builder clearSessionEndTs() {
        if (sessionEndTsBuilder_ == null) {
          sessionEndTs_ = null;
          onChanged();
        } else {
          sessionEndTs_ = null;
          sessionEndTsBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue session_end_ts = 2;</code>
       */
      public com.google.protobuf.StringValue.Builder getSessionEndTsBuilder() {
        
        onChanged();
        return getSessionEndTsFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.StringValue session_end_ts = 2;</code>
       */
      public com.google.protobuf.StringValueOrBuilder getSessionEndTsOrBuilder() {
        if (sessionEndTsBuilder_ != null) {
          return sessionEndTsBuilder_.getMessageOrBuilder();
        } else {
          return sessionEndTs_ == null ?
              com.google.protobuf.StringValue.getDefaultInstance() : sessionEndTs_;
        }
      }
      /**
       * <code>.google.protobuf.StringValue session_end_ts = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
          getSessionEndTsFieldBuilder() {
        if (sessionEndTsBuilder_ == null) {
          sessionEndTsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                  getSessionEndTs(),
                  getParentForChildren(),
                  isClean());
          sessionEndTs_ = null;
        }
        return sessionEndTsBuilder_;
      }

      private com.google.protobuf.Int64Value clickCount_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder> clickCountBuilder_;
      /**
       * <code>.google.protobuf.Int64Value click_count = 3;</code>
       * @return Whether the clickCount field is set.
       */
      public boolean hasClickCount() {
        return clickCountBuilder_ != null || clickCount_ != null;
      }
      /**
       * <code>.google.protobuf.Int64Value click_count = 3;</code>
       * @return The clickCount.
       */
      public com.google.protobuf.Int64Value getClickCount() {
        if (clickCountBuilder_ == null) {
          return clickCount_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : clickCount_;
        } else {
          return clickCountBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Int64Value click_count = 3;</code>
       */
      public Builder setClickCount(com.google.protobuf.Int64Value value) {
        if (clickCountBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          clickCount_ = value;
          onChanged();
        } else {
          clickCountBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Int64Value click_count = 3;</code>
       */
      public Builder setClickCount(
          com.google.protobuf.Int64Value.Builder builderForValue) {
        if (clickCountBuilder_ == null) {
          clickCount_ = builderForValue.build();
          onChanged();
        } else {
          clickCountBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Int64Value click_count = 3;</code>
       */
      public Builder mergeClickCount(com.google.protobuf.Int64Value value) {
        if (clickCountBuilder_ == null) {
          if (clickCount_ != null) {
            clickCount_ =
              com.google.protobuf.Int64Value.newBuilder(clickCount_).mergeFrom(value).buildPartial();
          } else {
            clickCount_ = value;
          }
          onChanged();
        } else {
          clickCountBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Int64Value click_count = 3;</code>
       */
      public Builder clearClickCount() {
        if (clickCountBuilder_ == null) {
          clickCount_ = null;
          onChanged();
        } else {
          clickCount_ = null;
          clickCountBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Int64Value click_count = 3;</code>
       */
      public com.google.protobuf.Int64Value.Builder getClickCountBuilder() {
        
        onChanged();
        return getClickCountFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Int64Value click_count = 3;</code>
       */
      public com.google.protobuf.Int64ValueOrBuilder getClickCountOrBuilder() {
        if (clickCountBuilder_ != null) {
          return clickCountBuilder_.getMessageOrBuilder();
        } else {
          return clickCount_ == null ?
              com.google.protobuf.Int64Value.getDefaultInstance() : clickCount_;
        }
      }
      /**
       * <code>.google.protobuf.Int64Value click_count = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder> 
          getClickCountFieldBuilder() {
        if (clickCountBuilder_ == null) {
          clickCountBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder>(
                  getClickCount(),
                  getParentForChildren(),
                  isClean());
          clickCount_ = null;
        }
        return clickCountBuilder_;
      }

      private com.google.protobuf.Int64Value sessionLengthMs_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder> sessionLengthMsBuilder_;
      /**
       * <code>.google.protobuf.Int64Value session_length_ms = 4;</code>
       * @return Whether the sessionLengthMs field is set.
       */
      public boolean hasSessionLengthMs() {
        return sessionLengthMsBuilder_ != null || sessionLengthMs_ != null;
      }
      /**
       * <code>.google.protobuf.Int64Value session_length_ms = 4;</code>
       * @return The sessionLengthMs.
       */
      public com.google.protobuf.Int64Value getSessionLengthMs() {
        if (sessionLengthMsBuilder_ == null) {
          return sessionLengthMs_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : sessionLengthMs_;
        } else {
          return sessionLengthMsBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Int64Value session_length_ms = 4;</code>
       */
      public Builder setSessionLengthMs(com.google.protobuf.Int64Value value) {
        if (sessionLengthMsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          sessionLengthMs_ = value;
          onChanged();
        } else {
          sessionLengthMsBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Int64Value session_length_ms = 4;</code>
       */
      public Builder setSessionLengthMs(
          com.google.protobuf.Int64Value.Builder builderForValue) {
        if (sessionLengthMsBuilder_ == null) {
          sessionLengthMs_ = builderForValue.build();
          onChanged();
        } else {
          sessionLengthMsBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Int64Value session_length_ms = 4;</code>
       */
      public Builder mergeSessionLengthMs(com.google.protobuf.Int64Value value) {
        if (sessionLengthMsBuilder_ == null) {
          if (sessionLengthMs_ != null) {
            sessionLengthMs_ =
              com.google.protobuf.Int64Value.newBuilder(sessionLengthMs_).mergeFrom(value).buildPartial();
          } else {
            sessionLengthMs_ = value;
          }
          onChanged();
        } else {
          sessionLengthMsBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Int64Value session_length_ms = 4;</code>
       */
      public Builder clearSessionLengthMs() {
        if (sessionLengthMsBuilder_ == null) {
          sessionLengthMs_ = null;
          onChanged();
        } else {
          sessionLengthMs_ = null;
          sessionLengthMsBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Int64Value session_length_ms = 4;</code>
       */
      public com.google.protobuf.Int64Value.Builder getSessionLengthMsBuilder() {
        
        onChanged();
        return getSessionLengthMsFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Int64Value session_length_ms = 4;</code>
       */
      public com.google.protobuf.Int64ValueOrBuilder getSessionLengthMsOrBuilder() {
        if (sessionLengthMsBuilder_ != null) {
          return sessionLengthMsBuilder_.getMessageOrBuilder();
        } else {
          return sessionLengthMs_ == null ?
              com.google.protobuf.Int64Value.getDefaultInstance() : sessionLengthMs_;
        }
      }
      /**
       * <code>.google.protobuf.Int64Value session_length_ms = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder> 
          getSessionLengthMsFieldBuilder() {
        if (sessionLengthMsBuilder_ == null) {
          sessionLengthMsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder>(
                  getSessionLengthMs(),
                  getParentForChildren(),
                  isClean());
          sessionLengthMs_ = null;
        }
        return sessionLengthMsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:io.confluent.training.proto.ClicksCount)
    }

    // @@protoc_insertion_point(class_scope:io.confluent.training.proto.ClicksCount)
    private static final io.confluent.training.proto.ClicksCountProtos.ClicksCount DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.confluent.training.proto.ClicksCountProtos.ClicksCount();
    }

    public static io.confluent.training.proto.ClicksCountProtos.ClicksCount getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ClicksCount>
        PARSER = new com.google.protobuf.AbstractParser<ClicksCount>() {
      @java.lang.Override
      public ClicksCount parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ClicksCount(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ClicksCount> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ClicksCount> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.confluent.training.proto.ClicksCountProtos.ClicksCount getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_confluent_training_proto_ClicksCount_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_confluent_training_proto_ClicksCount_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021clicksCount.proto\022\033io.confluent.traini" +
      "ng.proto\032\036google/protobuf/wrappers.proto" +
      "\"\345\001\n\013ClicksCount\0226\n\020session_start_ts\030\001 \001" +
      "(\0132\034.google.protobuf.StringValue\0224\n\016sess" +
      "ion_end_ts\030\002 \001(\0132\034.google.protobuf.Strin" +
      "gValue\0220\n\013click_count\030\003 \001(\0132\033.google.pro" +
      "tobuf.Int64Value\0226\n\021session_length_ms\030\004 " +
      "\001(\0132\033.google.protobuf.Int64ValueB\023B\021Clic" +
      "ksCountProtosb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
        });
    internal_static_io_confluent_training_proto_ClicksCount_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_confluent_training_proto_ClicksCount_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_confluent_training_proto_ClicksCount_descriptor,
        new java.lang.String[] { "SessionStartTs", "SessionEndTs", "ClickCount", "SessionLengthMs", });
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
