// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clicks.proto

package io.confluent.training.proto;

public final class ClicksProtos {
  private ClicksProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ClicksOrBuilder extends
      // @@protoc_insertion_point(interface_extends:io.confluent.training.proto.Clicks)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.google.protobuf.StringValue ip = 1;</code>
     * @return Whether the ip field is set.
     */
    boolean hasIp();
    /**
     * <code>.google.protobuf.StringValue ip = 1;</code>
     * @return The ip.
     */
    com.google.protobuf.StringValue getIp();
    /**
     * <code>.google.protobuf.StringValue ip = 1;</code>
     */
    com.google.protobuf.StringValueOrBuilder getIpOrBuilder();

    /**
     * <code>.google.protobuf.Int64Value timestamp = 2;</code>
     * @return Whether the timestamp field is set.
     */
    boolean hasTimestamp();
    /**
     * <code>.google.protobuf.Int64Value timestamp = 2;</code>
     * @return The timestamp.
     */
    com.google.protobuf.Int64Value getTimestamp();
    /**
     * <code>.google.protobuf.Int64Value timestamp = 2;</code>
     */
    com.google.protobuf.Int64ValueOrBuilder getTimestampOrBuilder();

    /**
     * <code>.google.protobuf.StringValue url = 3;</code>
     * @return Whether the url field is set.
     */
    boolean hasUrl();
    /**
     * <code>.google.protobuf.StringValue url = 3;</code>
     * @return The url.
     */
    com.google.protobuf.StringValue getUrl();
    /**
     * <code>.google.protobuf.StringValue url = 3;</code>
     */
    com.google.protobuf.StringValueOrBuilder getUrlOrBuilder();
  }
  /**
   * Protobuf type {@code io.confluent.training.proto.Clicks}
   */
  public static final class Clicks extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:io.confluent.training.proto.Clicks)
      ClicksOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Clicks.newBuilder() to construct.
    private Clicks(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Clicks() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Clicks();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Clicks(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.StringValue.Builder subBuilder = null;
              if (ip_ != null) {
                subBuilder = ip_.toBuilder();
              }
              ip_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(ip_);
                ip_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              com.google.protobuf.Int64Value.Builder subBuilder = null;
              if (timestamp_ != null) {
                subBuilder = timestamp_.toBuilder();
              }
              timestamp_ = input.readMessage(com.google.protobuf.Int64Value.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(timestamp_);
                timestamp_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              com.google.protobuf.StringValue.Builder subBuilder = null;
              if (url_ != null) {
                subBuilder = url_.toBuilder();
              }
              url_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(url_);
                url_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.confluent.training.proto.ClicksProtos.internal_static_io_confluent_training_proto_Clicks_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.confluent.training.proto.ClicksProtos.internal_static_io_confluent_training_proto_Clicks_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.confluent.training.proto.ClicksProtos.Clicks.class, io.confluent.training.proto.ClicksProtos.Clicks.Builder.class);
    }

    public static final int IP_FIELD_NUMBER = 1;
    private com.google.protobuf.StringValue ip_;
    /**
     * <code>.google.protobuf.StringValue ip = 1;</code>
     * @return Whether the ip field is set.
     */
    @java.lang.Override
    public boolean hasIp() {
      return ip_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue ip = 1;</code>
     * @return The ip.
     */
    @java.lang.Override
    public com.google.protobuf.StringValue getIp() {
      return ip_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : ip_;
    }
    /**
     * <code>.google.protobuf.StringValue ip = 1;</code>
     */
    @java.lang.Override
    public com.google.protobuf.StringValueOrBuilder getIpOrBuilder() {
      return getIp();
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private com.google.protobuf.Int64Value timestamp_;
    /**
     * <code>.google.protobuf.Int64Value timestamp = 2;</code>
     * @return Whether the timestamp field is set.
     */
    @java.lang.Override
    public boolean hasTimestamp() {
      return timestamp_ != null;
    }
    /**
     * <code>.google.protobuf.Int64Value timestamp = 2;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public com.google.protobuf.Int64Value getTimestamp() {
      return timestamp_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : timestamp_;
    }
    /**
     * <code>.google.protobuf.Int64Value timestamp = 2;</code>
     */
    @java.lang.Override
    public com.google.protobuf.Int64ValueOrBuilder getTimestampOrBuilder() {
      return getTimestamp();
    }

    public static final int URL_FIELD_NUMBER = 3;
    private com.google.protobuf.StringValue url_;
    /**
     * <code>.google.protobuf.StringValue url = 3;</code>
     * @return Whether the url field is set.
     */
    @java.lang.Override
    public boolean hasUrl() {
      return url_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue url = 3;</code>
     * @return The url.
     */
    @java.lang.Override
    public com.google.protobuf.StringValue getUrl() {
      return url_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : url_;
    }
    /**
     * <code>.google.protobuf.StringValue url = 3;</code>
     */
    @java.lang.Override
    public com.google.protobuf.StringValueOrBuilder getUrlOrBuilder() {
      return getUrl();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (ip_ != null) {
        output.writeMessage(1, getIp());
      }
      if (timestamp_ != null) {
        output.writeMessage(2, getTimestamp());
      }
      if (url_ != null) {
        output.writeMessage(3, getUrl());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (ip_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getIp());
      }
      if (timestamp_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getTimestamp());
      }
      if (url_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getUrl());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.confluent.training.proto.ClicksProtos.Clicks)) {
        return super.equals(obj);
      }
      io.confluent.training.proto.ClicksProtos.Clicks other = (io.confluent.training.proto.ClicksProtos.Clicks) obj;

      if (hasIp() != other.hasIp()) return false;
      if (hasIp()) {
        if (!getIp()
            .equals(other.getIp())) return false;
      }
      if (hasTimestamp() != other.hasTimestamp()) return false;
      if (hasTimestamp()) {
        if (!getTimestamp()
            .equals(other.getTimestamp())) return false;
      }
      if (hasUrl() != other.hasUrl()) return false;
      if (hasUrl()) {
        if (!getUrl()
            .equals(other.getUrl())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasIp()) {
        hash = (37 * hash) + IP_FIELD_NUMBER;
        hash = (53 * hash) + getIp().hashCode();
      }
      if (hasTimestamp()) {
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + getTimestamp().hashCode();
      }
      if (hasUrl()) {
        hash = (37 * hash) + URL_FIELD_NUMBER;
        hash = (53 * hash) + getUrl().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.confluent.training.proto.ClicksProtos.Clicks parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.confluent.training.proto.ClicksProtos.Clicks parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.confluent.training.proto.ClicksProtos.Clicks parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.confluent.training.proto.ClicksProtos.Clicks parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.confluent.training.proto.ClicksProtos.Clicks parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.confluent.training.proto.ClicksProtos.Clicks parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.confluent.training.proto.ClicksProtos.Clicks parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.confluent.training.proto.ClicksProtos.Clicks parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.confluent.training.proto.ClicksProtos.Clicks parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.confluent.training.proto.ClicksProtos.Clicks parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.confluent.training.proto.ClicksProtos.Clicks parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.confluent.training.proto.ClicksProtos.Clicks parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.confluent.training.proto.ClicksProtos.Clicks prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code io.confluent.training.proto.Clicks}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:io.confluent.training.proto.Clicks)
        io.confluent.training.proto.ClicksProtos.ClicksOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.confluent.training.proto.ClicksProtos.internal_static_io_confluent_training_proto_Clicks_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.confluent.training.proto.ClicksProtos.internal_static_io_confluent_training_proto_Clicks_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.confluent.training.proto.ClicksProtos.Clicks.class, io.confluent.training.proto.ClicksProtos.Clicks.Builder.class);
      }

      // Construct using io.confluent.training.proto.ClicksProtos.Clicks.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (ipBuilder_ == null) {
          ip_ = null;
        } else {
          ip_ = null;
          ipBuilder_ = null;
        }
        if (timestampBuilder_ == null) {
          timestamp_ = null;
        } else {
          timestamp_ = null;
          timestampBuilder_ = null;
        }
        if (urlBuilder_ == null) {
          url_ = null;
        } else {
          url_ = null;
          urlBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.confluent.training.proto.ClicksProtos.internal_static_io_confluent_training_proto_Clicks_descriptor;
      }

      @java.lang.Override
      public io.confluent.training.proto.ClicksProtos.Clicks getDefaultInstanceForType() {
        return io.confluent.training.proto.ClicksProtos.Clicks.getDefaultInstance();
      }

      @java.lang.Override
      public io.confluent.training.proto.ClicksProtos.Clicks build() {
        io.confluent.training.proto.ClicksProtos.Clicks result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.confluent.training.proto.ClicksProtos.Clicks buildPartial() {
        io.confluent.training.proto.ClicksProtos.Clicks result = new io.confluent.training.proto.ClicksProtos.Clicks(this);
        if (ipBuilder_ == null) {
          result.ip_ = ip_;
        } else {
          result.ip_ = ipBuilder_.build();
        }
        if (timestampBuilder_ == null) {
          result.timestamp_ = timestamp_;
        } else {
          result.timestamp_ = timestampBuilder_.build();
        }
        if (urlBuilder_ == null) {
          result.url_ = url_;
        } else {
          result.url_ = urlBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.confluent.training.proto.ClicksProtos.Clicks) {
          return mergeFrom((io.confluent.training.proto.ClicksProtos.Clicks)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.confluent.training.proto.ClicksProtos.Clicks other) {
        if (other == io.confluent.training.proto.ClicksProtos.Clicks.getDefaultInstance()) return this;
        if (other.hasIp()) {
          mergeIp(other.getIp());
        }
        if (other.hasTimestamp()) {
          mergeTimestamp(other.getTimestamp());
        }
        if (other.hasUrl()) {
          mergeUrl(other.getUrl());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.confluent.training.proto.ClicksProtos.Clicks parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.confluent.training.proto.ClicksProtos.Clicks) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.StringValue ip_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> ipBuilder_;
      /**
       * <code>.google.protobuf.StringValue ip = 1;</code>
       * @return Whether the ip field is set.
       */
      public boolean hasIp() {
        return ipBuilder_ != null || ip_ != null;
      }
      /**
       * <code>.google.protobuf.StringValue ip = 1;</code>
       * @return The ip.
       */
      public com.google.protobuf.StringValue getIp() {
        if (ipBuilder_ == null) {
          return ip_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : ip_;
        } else {
          return ipBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.StringValue ip = 1;</code>
       */
      public Builder setIp(com.google.protobuf.StringValue value) {
        if (ipBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ip_ = value;
          onChanged();
        } else {
          ipBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue ip = 1;</code>
       */
      public Builder setIp(
          com.google.protobuf.StringValue.Builder builderForValue) {
        if (ipBuilder_ == null) {
          ip_ = builderForValue.build();
          onChanged();
        } else {
          ipBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue ip = 1;</code>
       */
      public Builder mergeIp(com.google.protobuf.StringValue value) {
        if (ipBuilder_ == null) {
          if (ip_ != null) {
            ip_ =
              com.google.protobuf.StringValue.newBuilder(ip_).mergeFrom(value).buildPartial();
          } else {
            ip_ = value;
          }
          onChanged();
        } else {
          ipBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue ip = 1;</code>
       */
      public Builder clearIp() {
        if (ipBuilder_ == null) {
          ip_ = null;
          onChanged();
        } else {
          ip_ = null;
          ipBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue ip = 1;</code>
       */
      public com.google.protobuf.StringValue.Builder getIpBuilder() {
        
        onChanged();
        return getIpFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.StringValue ip = 1;</code>
       */
      public com.google.protobuf.StringValueOrBuilder getIpOrBuilder() {
        if (ipBuilder_ != null) {
          return ipBuilder_.getMessageOrBuilder();
        } else {
          return ip_ == null ?
              com.google.protobuf.StringValue.getDefaultInstance() : ip_;
        }
      }
      /**
       * <code>.google.protobuf.StringValue ip = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
          getIpFieldBuilder() {
        if (ipBuilder_ == null) {
          ipBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                  getIp(),
                  getParentForChildren(),
                  isClean());
          ip_ = null;
        }
        return ipBuilder_;
      }

      private com.google.protobuf.Int64Value timestamp_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder> timestampBuilder_;
      /**
       * <code>.google.protobuf.Int64Value timestamp = 2;</code>
       * @return Whether the timestamp field is set.
       */
      public boolean hasTimestamp() {
        return timestampBuilder_ != null || timestamp_ != null;
      }
      /**
       * <code>.google.protobuf.Int64Value timestamp = 2;</code>
       * @return The timestamp.
       */
      public com.google.protobuf.Int64Value getTimestamp() {
        if (timestampBuilder_ == null) {
          return timestamp_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : timestamp_;
        } else {
          return timestampBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Int64Value timestamp = 2;</code>
       */
      public Builder setTimestamp(com.google.protobuf.Int64Value value) {
        if (timestampBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          timestamp_ = value;
          onChanged();
        } else {
          timestampBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Int64Value timestamp = 2;</code>
       */
      public Builder setTimestamp(
          com.google.protobuf.Int64Value.Builder builderForValue) {
        if (timestampBuilder_ == null) {
          timestamp_ = builderForValue.build();
          onChanged();
        } else {
          timestampBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Int64Value timestamp = 2;</code>
       */
      public Builder mergeTimestamp(com.google.protobuf.Int64Value value) {
        if (timestampBuilder_ == null) {
          if (timestamp_ != null) {
            timestamp_ =
              com.google.protobuf.Int64Value.newBuilder(timestamp_).mergeFrom(value).buildPartial();
          } else {
            timestamp_ = value;
          }
          onChanged();
        } else {
          timestampBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Int64Value timestamp = 2;</code>
       */
      public Builder clearTimestamp() {
        if (timestampBuilder_ == null) {
          timestamp_ = null;
          onChanged();
        } else {
          timestamp_ = null;
          timestampBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Int64Value timestamp = 2;</code>
       */
      public com.google.protobuf.Int64Value.Builder getTimestampBuilder() {
        
        onChanged();
        return getTimestampFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Int64Value timestamp = 2;</code>
       */
      public com.google.protobuf.Int64ValueOrBuilder getTimestampOrBuilder() {
        if (timestampBuilder_ != null) {
          return timestampBuilder_.getMessageOrBuilder();
        } else {
          return timestamp_ == null ?
              com.google.protobuf.Int64Value.getDefaultInstance() : timestamp_;
        }
      }
      /**
       * <code>.google.protobuf.Int64Value timestamp = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder> 
          getTimestampFieldBuilder() {
        if (timestampBuilder_ == null) {
          timestampBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder>(
                  getTimestamp(),
                  getParentForChildren(),
                  isClean());
          timestamp_ = null;
        }
        return timestampBuilder_;
      }

      private com.google.protobuf.StringValue url_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> urlBuilder_;
      /**
       * <code>.google.protobuf.StringValue url = 3;</code>
       * @return Whether the url field is set.
       */
      public boolean hasUrl() {
        return urlBuilder_ != null || url_ != null;
      }
      /**
       * <code>.google.protobuf.StringValue url = 3;</code>
       * @return The url.
       */
      public com.google.protobuf.StringValue getUrl() {
        if (urlBuilder_ == null) {
          return url_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : url_;
        } else {
          return urlBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.StringValue url = 3;</code>
       */
      public Builder setUrl(com.google.protobuf.StringValue value) {
        if (urlBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          url_ = value;
          onChanged();
        } else {
          urlBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue url = 3;</code>
       */
      public Builder setUrl(
          com.google.protobuf.StringValue.Builder builderForValue) {
        if (urlBuilder_ == null) {
          url_ = builderForValue.build();
          onChanged();
        } else {
          urlBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue url = 3;</code>
       */
      public Builder mergeUrl(com.google.protobuf.StringValue value) {
        if (urlBuilder_ == null) {
          if (url_ != null) {
            url_ =
              com.google.protobuf.StringValue.newBuilder(url_).mergeFrom(value).buildPartial();
          } else {
            url_ = value;
          }
          onChanged();
        } else {
          urlBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue url = 3;</code>
       */
      public Builder clearUrl() {
        if (urlBuilder_ == null) {
          url_ = null;
          onChanged();
        } else {
          url_ = null;
          urlBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue url = 3;</code>
       */
      public com.google.protobuf.StringValue.Builder getUrlBuilder() {
        
        onChanged();
        return getUrlFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.StringValue url = 3;</code>
       */
      public com.google.protobuf.StringValueOrBuilder getUrlOrBuilder() {
        if (urlBuilder_ != null) {
          return urlBuilder_.getMessageOrBuilder();
        } else {
          return url_ == null ?
              com.google.protobuf.StringValue.getDefaultInstance() : url_;
        }
      }
      /**
       * <code>.google.protobuf.StringValue url = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
          getUrlFieldBuilder() {
        if (urlBuilder_ == null) {
          urlBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                  getUrl(),
                  getParentForChildren(),
                  isClean());
          url_ = null;
        }
        return urlBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:io.confluent.training.proto.Clicks)
    }

    // @@protoc_insertion_point(class_scope:io.confluent.training.proto.Clicks)
    private static final io.confluent.training.proto.ClicksProtos.Clicks DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.confluent.training.proto.ClicksProtos.Clicks();
    }

    public static io.confluent.training.proto.ClicksProtos.Clicks getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Clicks>
        PARSER = new com.google.protobuf.AbstractParser<Clicks>() {
      @java.lang.Override
      public Clicks parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Clicks(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Clicks> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Clicks> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.confluent.training.proto.ClicksProtos.Clicks getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_confluent_training_proto_Clicks_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_confluent_training_proto_Clicks_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014clicks.proto\022\033io.confluent.training.pr" +
      "oto\032\036google/protobuf/wrappers.proto\"\215\001\n\006" +
      "Clicks\022(\n\002ip\030\001 \001(\0132\034.google.protobuf.Str" +
      "ingValue\022.\n\ttimestamp\030\002 \001(\0132\033.google.pro" +
      "tobuf.Int64Value\022)\n\003url\030\003 \001(\0132\034.google.p" +
      "rotobuf.StringValueB\016B\014ClicksProtosb\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
        });
    internal_static_io_confluent_training_proto_Clicks_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_confluent_training_proto_Clicks_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_confluent_training_proto_Clicks_descriptor,
        new java.lang.String[] { "Ip", "Timestamp", "Url", });
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
