version: '3.5'
services:
  zookeeper:
    image: "confluentinc/cp-zookeeper:5.3.0"
    hostname: zookeeper
    container_name: zookeeper
    networks:
      - streams-net
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: "confluentinc/cp-enterprise-kafka:5.3.0"
    hostname: kafka
    container_name: kafka
    networks:
      - streams-net
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 101
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 100

  schema-registry:
    image: "confluentinc/cp-schema-registry:5.3.0"
    hostname: schema-registry
    container_name: schema-registry
    networks:
      - streams-net
    ports:
      - 8081:8081
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka:9092
      SCHEMA_REGISTRY_LISTENERS: http://schema-registry:8081

  tools:
    image: cnfltraining/training-tools:19.06
    hostname: tools
    container_name: tools
    networks:
      - streams-net
    volumes:
      - .:/root/confluent-streams/labs/monitoring
    working_dir: /root/confluent-streams/labs/monitoring
    command: /bin/bash
    tty: true


networks:
  streams-net:
